services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: farol_backend
    environment:
      PYTHONPATH: /app
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: http://backend:8000
    container_name: farol_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: farol_net
