services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: farol_backend
    working_dir: /app
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: farol_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./docs:/app/docs:ro
    command: sh -c "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0"
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
